# Generated by Django 4.2.3 on 2023-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='todo_desc',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='todos',
            name='todo_status',
            field=models.BooleanField(default=False),
        ),
    ]
